version: 2
jobs:
  build:
    machine: true
#      - image: circleci/golang:1.11.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:e7:07:40:e6:c0:8c:bc:72:b8:db:c9:36:b1:9c:e2"	   
      - checkout gauravgoyal
#      - run:
 #         command: go run hello.go
      - run: sudo apt-get install nginx
      - run: nginx -V
      - run: ifconfig	
