version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - checkout
      - run: go run hello.go
  test:
   build:
    machine:true
      - checkout
      - run: curl 127.0.0.1:8080
workflows:
  version: 2
  build_and_test:
    jobs:
      -build
      -test
