version: 2
jobs:
  buil:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - checkout
      - run: go run hello.go
  test:
   build:
    machine:true
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  build_and_test:
    jobs:
      -buil
      -test
