version: 2.0
defauts: &defaults
  docker:
  - image: ubuntu:18.04
  jobs:
  deploy-job:
    steps:
      - checkout
      - run:
          name: running commands
          command: |
            echo -e "private_key_file = ~/.ssh/id_rsa$FINGER_PRINT"
	    ssh-keyscan -H ec2-18-218-226-96.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
            ssh -i "private_key_file" ubuntu@ec2-18-218-226-96.us-east-2.compute.amazonaws.com
	    cd /home/ubuntu/hello_world
            go run hello.go &
            curl 127.0.0.1:8080


