version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "96:e7:07:40:e6:c0:8c:bc:72:b8:db:c9:36:b1:9c:e2"
      - checkout
      - run:
          command: go run hello.go
          background: true
      - run: curl 172.17.108.56:8080
