version: 2.0
defauts: &defaults
  docker:
  - image: ubuntu:18.04
jobs:
 build:
   docker:
   - image: ubuntu:18.04
   steps:
     - checkout
 deploy:
   docker:
   - image: ubuntu:18.04
   steps:
     - add_ssh_keys:
          fingerprints:
            - "ba:e6:c1:72:f4:af:86:87:1a:ee:91:2c:cb:36:85:75"
     - run:
         name: ssh and running
         command: |
           apt-get -yq update && apt-get -yqq install ssh
           cd 
           cd .ssh
           ssh-keyscan -H ec2-18-218-226-96.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
           echo -e "private_key_file = /root/.ssh/id_rsa_$FINGER_PRINT"
           echo -e "remote_user = ubuntu"
           ls -a
           chmod 400 id_rsa_bae6c172f4af86871aee912ccb368575
           ssh -i $private_key_file $remote_user@ec2-18-218-226-96.us-east-2.compute.amazonaws.com
           mkdir hello
           cd /home/ubuntu/hello_world
           go run hello.go &
           curl 127.0.0.1:8080
workflows:
 version: 2
 Example_Workflow:
  jobs:
   - build
   - deploy:
      requires:
       - build

