version: 2.0
defauts: &defaults
  docker:
  - image: ubuntu:18.04
  jobs:
  deploy-job:
    steps:
      - checkout
#      - add_ssh_keys:
#          fingerprints:
#            - "ba:e6:c1:72:f4:af:86:87:1a:ee:91:2c:cb:36:85:75"
      - run:
          name: running commands
          command: |
	    ssh $ssh_user@$ssh_host
            cd /home/ubuntu/hello_world
            go run hello.go &
            curl 127.0.0.1:8080


