version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are al$
      - image: circleci/golang:1.11.2 
# the primary container, where your job's commands are run
    steps:
     - checkout # check out the code in the project directory
      - run: go run hello.go




