version: 2.0
defauts: &defaults
  docker:
  - image: ubuntu:18.04
  jobs:
  deploy-job:
    steps:
      - checkout
      - run:
          name: running commands
          command: |
            cd /home/ubuntu/hello_world
            go run hello.go &
            curl 127.0.0.1:8080


